[project]
name = "chatwoot-locust-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.12.0",
    "locust>=2.42.1",
]
